In [1]:
import numpy as np

In [8]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
calculate=np.array([[0,1,2],[3,4,5],[6,7,8]])

# Mean

In [13]:
calculate.mean(axis=0)

array([3., 4., 5.])

In [14]:
calculate.mean(axis=1)

array([1., 4., 7.])

In [16]:
flattened=np.array([6,7,8])

In [18]:
flattened

array([6, 7, 8])

In [21]:
calculate.mean()

4.0

# Variance

In [22]:
calculate.var(axis=0)

array([6., 6., 6.])

In [23]:
calculate.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [24]:
calculate.var()

6.666666666666667

# Standard Deviation


In [26]:
calculate.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [27]:
calculate.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [28]:
calculate.std()

2.581988897471611

# Max

In [29]:
calculate.max(axis=0)

array([6, 7, 8])

In [30]:
calculate.max(axis=1)

array([2, 5, 8])

In [31]:
calculate.max()

8

# Min

In [32]:
calculate.min(axis=0)

array([0, 1, 2])

In [33]:
calculate.min(axis=1)

array([0, 3, 6])

In [34]:
calculate.min()

0

# Sum

In [35]:
calculate.sum(axis=0)

array([ 9, 12, 15])

In [36]:
calculate.sum(axis=1)

array([ 3, 12, 21])

In [37]:
calculate.sum()

36